---
- name: debian | installing squid
  apt:
    name: "{{ squid_package }}"
    state: "present"
  become: true

- name: debian | install packages for generate password
  apt:
    name: python-passlib
    state: present
