---
- name: redhat | Installing Squid (Non-Fedora)
  yum:
    name: "{{ squid_package }}"
    state: "present"
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | install packages for generate password
  yum:
    name: python-passlib
    state: present
